### ISSUE TITLE
Lack of some user data on "Recent Changes" page

### ISSUE THREAD

**Issue by jarosik** [pief/authsplit#6]
User data (email or real name) are not presented on the "recent changes" page. Only IP address is shown.
Conditions:
- Dokuwiki version: 2014-05-05 "Ponder Stibbons"
- Parameter "showuseras" is set to value other than "loginname"
- primary_authplugin: authad
- secondary_authplugin: authplain

**Comment by pief** [comment]
Closing this due to no reply.
