### ISSUE TITLE
Call to a member function logOff() issue

### ISSUE THREAD

**Issue by bug** [pief/authsplit#7]
Hi

I cloned an installed wiki on a new VPS and get a fatal error I never had before:

PHP Fatal error:  Call to a member function logOff() on a non-object in /www/docs/lib/plugins/authsplit/auth.php on line 294

I'm using an authsplit between ldap and plain, but as said it's a cloned wiki, so config is known to be ok, versions of DokuWiki (stable) and php also are the same. Any idea where that could come from?

**Comment by pief** [comment]
Is this still current or did you already find a way around?

**Comment by bug** [comment]
it was not related to split itself but to the LDAP auth being broken. I reinstalled everything cloning dokuwiki and the plugins and it worked like a charm, so I close that. Sorry for the noise.
