### ISSUE TITLE
Auto-create users should lowercase usernames

### ISSUE THREAD

**Issue by bug** [pief/authsplit#8]
I'm using a splitted LDAP/plain config. I see some mixed case login names populated by split in the users.auth.php file. For example:

loginname:xxxxxxx:Happy User:login@domain:users,othergroup,onemore
Loginname:xxxxxxx:Happy User:login@domain:users

First line was added manually, second is added by split. Shouldn't split lowercase the login before writing it to the users.auth.php file and thus in a case as above not add a line to the users file as there is already one there?

**Comment by pief** [comment]
Is this still current?

**Comment by bug** [comment]
Just pulled and checked: yes still the same.

**Comment by pief** [comment]
I guess the problem is that authldap appears to be case-insensitive whereas authplain is not. Which makes me wonder why authldap then doesn't provide a ```cleanUser()``` implementation.

Out of curiosity, what happens in a authldap-only configuration? Do you see users in mixed case in the user manager?

**Comment by bug** [comment]
You're right, I'm gonna file a request for a cleanUser() function in authldap. Thanks.
For your question, yes I see funny user "clones" :-)

**Comment by bug** [comment]
@pief see https://github.com/splitbrain/dokuwiki/issues/1965 your comment would be much appreciated.

**Comment by pief** [comment]
Please try this latest version, I added a new username_caseconversion setting for your use case :)

**Comment by bug** [comment]
It works. But I notice now that usernames containing a space character are also added to the users.auth.php file in my setup leading to a priviledge bypass. Shouldn't cleanuser() remove any space char in the username provided?

**Comment by pief** [comment]
Aside from the fact that that would be a totally different bug (changing case vs. special characters): no. It is perfectly acceptable for some authentication backends to allow spaces (or other special characters) in usernames. For those, a user "TheUser" is someone different from "The User", so we can't just blindly interfere with that.

As for your particular setup, I do not understand exactly what you're doing yet. What is the state of users.auth.php before you're authenticating, as who/what are you authenticating and what is the state of users.auth.php afterwards? 

By the way, you will ALWAYS have a privilege bypass unless you configure the default user group to be restrictive enough. It is IMO bad security design if the default user group has more privileges than some user should actually have later on.
