### ISSUE TITLE
API compatibility to DokuWiki Release 2017-02-19a "Frusterick Manners"

### ISSUE THREAD

**Issue by danieldietsch** [pief/authsplit#9]
With the current DokuWiki release 2017-02-19a "Frusterick Manners" and PHP7.0 I get the following warning using authsplit: 
`Warning: Declaration of auth_plugin_authsplit::getUserData($user) should be compatible with DokuWiki_Auth_Plugin::getUserData($user, $requireGroups = true) in .../lib/plugins/authsplit/auth.php on line 12`

**Comment by pief** [comment]
Thanks for reporting, please feel free to reopen if the error persists.

**Comment by danieldietsch** [comment]
Thanks for the quick fix! Its working now.

**Comment by pief** [comment]
I made a small mistake (asking the primary auth plugin for group information) and pushed some more commits, could you test once more, please?

**Comment by danieldietsch** [comment]
Ok, I updated again and it still looks good. But as my instance does not use group information, I did not really notice any difference.

**Comment by pief** [comment]
Ok, thanks nevertheless :)
